spring:
  application:
    name: inventory-service

  # Datasource configuration for H2 in-memory database
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always  

  # JPA (Hibernate) settings
  jpa:
    hibernate:
      ddl-auto: update      
    show-sql: true         
    database-platform: org.hibernate.dialect.H2Dialect

  # H2 console settings
  h2:
    console:
      enabled: true         
      path: /h2-console  
  kafka:
	bootstrap-servers: localhost:9092  
	# Producer configuration
	producer:
		key-serializer: org.apache.kafka.common.serialization.StringSerializer
		value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
		topic: low-inventory-topic

	    # Consumer configuration
	consumer:
	 	group-id: low-inventory-group        # Consumer group ID
	    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
	    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer	   

# Swagger configuration via Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs          
  swagger-ui:
    path: /swagger-ui.html   
    operationsSorter: method 
    tagsSorter: alpha        
  info:
    title: Inventory Service API's'
    description: API documentation for Inventory Service
    version: v1
	
	
